sonar.projectKey=PaperSync
sonar.projectName=PaperSync
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.13

sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/static/**,**/templates/**
sonar.test.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml

# Fail the pipeline if the Quality Gate is not passed
sonar.qualitygate.wait=true
